"""
writer.py
Writes AI-generated markdown back into the Obsidian vault's
🤖 AI Insights/ folder, with timestamps and proper formatting.
"""

from pathlib import Path
from datetime import datetime
from vault_reader import ensure_insights_folder


def _header(title: str, generated_at: str) -> str:
    return (
        f"---\n"
        f"generated: {generated_at}\n"
        f"source: Hermes AI\n"
        f"---\n\n"
        f"> [!NOTE] Auto-generated by Hermes AI on {generated_at}\n\n"
        f"# {title}\n\n"
    )


def write_insight(filename: str, title: str, content: str) -> Path:
    """Write a markdown insight file into the AI Insights folder."""
    folder = ensure_insights_folder()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    out = folder / f"{filename}.md"
    out.write_text(
        _header(title, now) + content,
        encoding="utf-8",
    )
    return out


def write_pattern_analysis(content: str) -> Path:
    return write_insight("Pattern Analysis", "🔍 Trade Pattern Analysis", content)


def write_daily_debrief(date: str, content: str) -> Path:
    return write_insight(f"Debrief {date}", f"📅 Daily Debrief — {date}", content)


def write_weekly_review(week_label: str, content: str) -> Path:
    safe_label = week_label.replace(" ", "_").replace("/", "-")
    return write_insight(f"Weekly Review {safe_label}", f"📝 Weekly Review — {week_label}", content)


def write_watchlist_notes(notes: dict[str, str]) -> Path:
    """Write per-stock coaching notes into a single Watchlist Insights file."""
    folder = ensure_insights_folder()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = [
        f"---\ngenerated: {now}\nsource: Hermes AI\n---\n",
        f"> [!NOTE] Auto-generated by Hermes AI on {now}\n",
        "# 🎯 Watchlist Coaching Notes\n",
    ]
    for stock, note in notes.items():
        lines.append(f"\n## {stock}\n\n{note}\n\n---\n")
    out = folder / "Watchlist Insights.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def write_memory_summary(memory: dict) -> Path:
    """Write a human-readable summary of Hermes's learned memory."""
    folder = ensure_insights_folder()
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    patterns = memory.get("patterns", [])
    emotional = memory.get("emotional_flags", [])
    best = memory.get("best_setups", [])
    worst = memory.get("worst_setups", [])

    lines = [
        f"---\ngenerated: {now}\nsource: Hermes AI\n---\n",
        f"> [!NOTE] Hermes's accumulated knowledge about your trading — updated {now}\n",
        "# 🧠 Hermes Memory — What I've Learned About You\n",
        f"\n**Total trades analysed**: {memory.get('total_trades_seen', 0)}",
        f"\n**Last updated**: {memory.get('last_updated', 'Never')}\n",
        "\n## 📊 Trading Patterns\n",
    ]
    if patterns:
        for p in patterns:
            lines.append(f"- {p}")
    else:
        lines.append("- Not enough data yet. Keep journaling!")

    lines.append("\n\n## ⚠️ Emotional Flags\n")
    if emotional:
        for e in emotional:
            lines.append(f"- {e}")
    else:
        lines.append("- None identified yet.")

    lines.append("\n\n## ✅ Best Setups\n")
    if best:
        for b in best:
            lines.append(f"- {b}")
    else:
        lines.append("- Keep trading to discover your edge.")

    lines.append("\n\n## ❌ Problem Setups\n")
    if worst:
        for w in worst:
            lines.append(f"- {w}")
    else:
        lines.append("- None identified yet.")

    out = folder / "Hermes Memory.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out
